name: "Update DevOps Work Item"
on:
  pull_request:
    types: [opened, ready_for_review]
jobs:
  update-devops-workitem:
    runs-on: ubuntu-latest
    steps:
      - name: "Update DevOps Work Item"
        uses: dc-ag/azure-devops-pr-notification@main
        with:
          repo-token: ${{ secrets.BAKERY_GITHUB_TOKEN }}
          devops-work-item-regex: /[0-9]+/
          set-to-state: "In Progress"
          add-pr-link: true
          dont-set-state-while-prs-open: false
          devops-organization: "volvocargroup"
          devops-pat: ${{ secrets.ADO_PAT }}  
          fail-on-error: true
